# Production Profile

# MySQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.devtools.add-properties=false

#Cache configuaration
spring.thymeleaf.cache=true